### ISSUE TITLE
Product page UI Should be Improve

### ISSUE THREAD

**Issue by JyotiKM29** [SurajjBhardwaj/twn#16]
<img width="1680" alt="Screenshot 2023-12-22 at 1 00 45 AM" src="https://github.com/SurajjBhardwaj/twn/assets/88364055/d88277d2-e291-4e8d-9ea0-e7b737ff8e4d">

- pictures are not align properly 
- text is not visible properly

**Comment by SurajjBhardwaj** [comment]
Yeah you're right, let's do it.

**Comment by SurajjBhardwaj** [comment]
you're right
